### ISSUE TITLE
Too much of blank space when you reduce the size

### ISSUE THREAD

**Issue by vanishakesswani** [jackburton79/bescreencapture#10]
![s1](https://cloud.githubusercontent.com/assets/24365311/21669818/016892ea-d335-11e6-9bff-ce2c433dd890.png)

**Comment by vanishakesswani** [comment]
Too much of space near "Start Recording" could be reduced .

**Comment by jackburton79** [comment]
Indeed

**Comment by jackburton79** [comment]
I've changed the layout and reduced the empty space near "Start Recording".
