### ISSUE TITLE
Select Region feature doesn't work

### ISSUE THREAD

**Issue by vanishakesswani** [jackburton79/bescreencapture#11]
Clicking Select Region gives me this : 
![s2](https://cloud.githubusercontent.com/assets/24365311/21669864/41e8d5dc-d335-11e6-8048-87c4a4d66924.png)

**Comment by jackburton79** [comment]
I know it's not really intuitive, but I think it's just a case of a wrongly rendered image. If you click and drag, you should be able to select the region.

**Comment by jackburton79** [comment]
I added some hint, could you try this version and see if it's a bit more user friendly ?
https://github.com/jackburton79/bescreencapture/releases/tag/20170105-snapshot

**Comment by jackburton79** [comment]
Hi, could you try the latest snapshot here ?
https://github.com/jackburton79/bescreencapture/releases/tag/20170105-snapshot

**Comment by vanishakesswani** [comment]
I am unable to install , not sure why .

**Comment by jackburton79** [comment]
Which version of haiku are you using ? (x86, x86_gcc2, x64)
You can check the about window to see if you are not sure.
I should have specified that this version is x86_gcc2.

**Comment by jackburton79** [comment]
Sorry, wrong ticket

**Comment by jackburton79** [comment]
This is what happens now when you click on "Select Region"
![bsc](https://cloud.githubusercontent.com/assets/3501519/21984792/e3807d08-dbf7-11e6-97b3-1accac738042.png)

**Comment by jackburton79** [comment]
> I am unable to install , not sure why .
Actually, I am unable to install the package, too.
I have no idea why.

**Comment by jackburton79** [comment]
Sorry, I had built an x86 package instead of a x86_gcc2 package.
Try this one: https://github.com/jackburton79/bescreencapture/releases/download/v2.3-pre/bescreencapture-2.3-1-x86_gcc2.hpkg
