### ISSUE TITLE
Cropped window on large fonts

### ISSUE THREAD

**Issue by vanishakesswani** [jackburton79/bescreencapture#12]
![crop](https://cloud.githubusercontent.com/assets/24365311/21669898/af29f572-d335-11e6-922d-d399017db5a8.png)
Using large fonts make's my window go out of the scope to see , a slidebar probably would help ?

**Comment by jackburton79** [comment]
I'll see what can be done.

**Comment by jackburton79** [comment]
I was also thinking about changing the layout completely, removing most stuff from the main window and putting everything inside menus or preference windows. The con is that this would make the application less immediate.

**Comment by scottmc** [comment]
Maybe this can be converted to use layout management?  Can we open a Google Code-In task for that or do you want to tackle it yourself?

**Comment by jackburton79** [comment]
Hi Scott,
It uses layout management already.
This is just a case of the window being too big to fit on the screen.

**Comment by jackburton79** [comment]
Honestly, I don't have a good idea on how to solve this.

**Comment by jackburton79** [comment]
Without rethinking the whole UI, I mean.

**Comment by jackburton79** [comment]
In the current UI, you can have a the font set at size 28 at 1920x1080 and the window almost fit. All buttons are visible, so I'm closing this.
