### ISSUE TITLE
Preview shows the app itself when using Select Window .

### ISSUE THREAD

**Issue by vanishakesswani** [jackburton79/bescreencapture#13]
![crop](https://cloud.githubusercontent.com/assets/24365311/21669936/1b299890-d336-11e6-92ee-d508047af6a1.png)
Even though I select some other app , the preview still shows bescreencapture .

**Comment by jackburton79** [comment]
Should be fixed in the snapshot. Can you confirm ?

**Comment by jackburton79** [comment]
Replying to my own post: no, it's not fixed.
It depends on the order/timing of received messages: if the message from the controller arrives after the message from the selection window, it overwrites the preview given by the latter.

**Comment by jackburton79** [comment]
Fixed.
