### ISSUE TITLE
Stop Recording key doesn't seem to work.

### ISSUE THREAD

**Issue by vanishakesswani** [jackburton79/bescreencapture#14]
I am on Haiku and trying to stop the recording but after using the given commands the recording doesn't stop .

**Comment by vanishakesswani** [comment]
![storage](https://cloud.githubusercontent.com/assets/24365311/21681948/aeb6cff6-d377-11e6-8362-90fb8d2cb6f9.png)
Doesn't look like that .
By the way I am using VM to run Haiku .
Using Microsoft Key instead of CMD key .

**Comment by jackburton79** [comment]
You mean the key combination, right ?
Did you install also the input filter package (bescreencapture-inputfilter) ?

**Comment by vanishakesswani** [comment]
Yes , I mean the key combination . 
Nope . Do I need to ?

**Comment by jackburton79** [comment]
To be able to use the key combination, yes, you need to.

**Comment by jackburton79** [comment]
I guess I should make it more esplicit :)

**Comment by jackburton79** [comment]
Any news on this ?

**Comment by jackburton79** [comment]
Closing due to no feedback. Please reopen if it still applies.
