### ISSUE TITLE
Pause / Resume support using key combination

### ISSUE THREAD

**Issue by vanishakesswani** [jackburton79/bescreencapture#16]
Pause / Resume support in bescreencapture would be of great help !

**Comment by jackburton79** [comment]
It's already there, but you have to use the deskbar control to pause/resume.

![pause _ resume support](https://cloud.githubusercontent.com/assets/3501519/21677600/28b185d6-d33b-11e6-8a1e-f808bf067e47.png)

**Comment by vanishakesswani** [comment]
Using key combination, sorry I forgot to mention earlier .

**Comment by jackburton79** [comment]
It should be possible to create a key combination using the Shortcut preflet which triggers pause/resume. Actually I'd like one day to drop the input filter requirement also for the record action and just be able to install a Shortcut handler.

**Comment by jackburton79** [comment]
I've implemented it and it will be available in the next version
