### ISSUE TITLE
Need new icons

### ISSUE THREAD

**Issue by richienyhus** [jackburton79/bescreencapture#2]
Both for the 3D app icon and for the 2D start, stop and pause.

Zumi's Icons might be worth looking at.

**Comment by jackburton79** [comment]
Icon by Pete Goodeve. Thanks!

[icon.zip](https://github.com/jackburton79/bescreencapture/files/499946/icon.zip)

**Comment by jackburton79** [comment]
Icon committed in 0ee84f58d88068651536fa1eac0dba20f6a8e175

**Comment by richienyhus** [comment]
@jackburton79 Have the 2D icons been updated?  (start, stop, resume and pause.)

**Comment by jackburton79** [comment]
2016-09-29 11:43 GMT+02:00 Richard Nyhus <notifications@github.com>:

> @jackburton79 <https://github.com/jackburton79> Have the 2D icons been
> updated? (start, stop, resume and pause.)
>
Right. No, they have not been updated. Do you think they need to be ?
In that case, I guess I should reopen this ticket.

**Comment by richienyhus** [comment]
I can't really remember what they look like now, but I think the were
homebrew/bespoke icons that I thought looked a little out of place on Haiku.

zumi's 2D icons:
http://zumi.xoom.it/myhaiku/btoolbar/index.html

**Comment by richienyhus** [comment]
![alt](https://web.archive.org/web/20160625214842/http://zumi.xoom.it/myhaiku/btoolbar/media%20playback%20start.png) ![alt](https://web.archive.org/web/20160625214850/http://zumi.xoom.it/myhaiku/btoolbar/media%20playback%20pause.png) ![alt](https://web.archive.org/web/20160625214748/http://zumi.xoom.it/myhaiku/btoolbar/media%20playback%20stop.png) ![alt](https://web.archive.org/web/20160625214829/http://zumi.xoom.it/myhaiku/btoolbar/media%20record.png)
