### ISSUE TITLE
Unable to play recorded videos with 'Windows media player'.

### ISSUE THREAD

**Issue by ysjodha1** [jackburton79/bescreencapture#20]
When I played the recorded videos in Windows Media Player it showed some Error but it worked fine in VLC media player.
Encoder Combination : 
 File Format : AVI
 Media Codec : MPEG-4 video
Suggestion : Add a 'MP4' file type too as it is more common and supported than avi and the likes.
![windows media player error](https://user-images.githubusercontent.com/33057532/33527519-5fe8046a-d878-11e7-9a4c-a7e675719d82.PNG)

**Comment by jackburton79** [comment]
I think this could be a problem of the haiku media kit, I've created a ticket in the haiku bug tracker.

**Comment by BogdanModolea** [comment]
You could edit the extension. For example, instead of .avi you can try .mp4 or .m2ts

**Comment by jackburton79** [comment]
The extension is taken from the codec definition.
Anyway, I noticed that the MPEG/Mpeg4 combo seems to work better than AVI/Mpeg4, at least on Haiku x64

**Comment by jackburton79** [comment]
Please try with a recent haiku image.
