### ISSUE TITLE
shows error ('General system error');

### ISSUE THREAD

**Issue by ysjodha1** [jackburton79/bescreencapture#21]
When source : Region is selected it sometimes shows this error ('General system error').
![general system error](https://user-images.githubusercontent.com/33057532/33527542-b9ca302a-d878-11e7-8266-65933da86d85.png)

**Comment by jackburton79** [comment]
Hi,
I think this problem has been fixed already.
Please try with version 2.3 (as soon as I release it).

**Comment by jackburton79** [comment]
v2.3.1 is out (only gcc2 binaries for now)

**Comment by skarmiglione** [comment]
Can it have a x64 verdion please? I am having the same issue here, and i want to use this soft so bad.

**Comment by jackburton79** [comment]
The 2.3.1 release contains x86-64 binaries, too.
https://github.com/jackburton79/bescreencapture/releases/tag/v2.3.1

**Comment by jackburton79** [comment]
Is this bug still valid with version 2.3.2 ?

**Comment by jackburton79** [comment]
Closing due to missing feedback.
