### ISSUE TITLE
the encoder timebase is not set 

### ISSUE THREAD

**Issue by skarmiglione** [jackburton79/bescreencapture#26]
Haiku x64
later of try to record the screen when i push stop record pop that warnings.

A problem has ocurred: general system error

[mpeg4 @ 0x1603340a940] The encoder timebase is not set.
[avi @ 0x160334f5040] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[avi @ 0x160334f5040] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpeg4 @ 0x1603340ae20] The encoder timebase is not set.
[mpeg4 @ 0x160335d1000] The encoder timebase is not set.
[avi @ 0x160335c9180] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[avi @ 0x160335c9180] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpeg4 @ 0x160335d14e0] The encoder timebase is not set.
[swscaler @ 0x1603352a9e0] deprecated pixel format used, make sure you did set range correctly
[mjpeg @ 0x160335d14e0] The encoder timebase is not set.
[avi @ 0x160335c9180] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[avi @ 0x160335c9180] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mjpeg @ 0x160335d1000] The encoder timebase is not set.
[swscaler @ 0x1603352a9e0] deprecated pixel format used, make sure you did set range correctly
[mjpeg @ 0x1603340ae20] The encoder timebase is not set.
[avi @ 0x160334da5c0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[avi @ 0x160334da5c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mjpeg @ 0x1603340a940] The encoder timebase is not set.
[swscaler @ 0x16033be0da0] deprecated pixel format used, make sure you did set range correctly
[mjpeg @ 0x160335d1000] The encoder timebase is not set.
[avi @ 0x1603357f480] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[avi @ 0x1603357f480] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mjpeg @ 0x160335d14e0] The encoder timebase is not set.
[swscaler @ 0x16033be0da0] deprecated pixel format used, make sure you did set range correctly
[mjpeg @ 0x16033574940] The encoder timebase is not set.
[avi @ 0x16033c2a2c0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[avi @ 0x16033c2a2c0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mjpeg @ 0x16033574e20] The encoder timebase is not set.

**Comment by jackburton79** [comment]
Which encoding format are you using ?
It seems the AVI / Mpeg4 is the only encoding format which works reliably in Haiku.

**Comment by skarmiglione** [comment]
I test with all the codec options and always is the same.

**Comment by skarmiglione** [comment]
[mpeg4 @ 0x1530c0df300] The encoder timebase is not set.
[ogv @ 0x1530c0d7480] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[ogv @ 0x1530c0d7480] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[ogv @ 0x1530c0d7480] Unsupported codec id in stream 0
[mpeg4 @ 0x1530bf38940] The encoder timebase is not set.
[mpeg @ 0x1530c01f040] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[mpeg @ 0x1530c01f040] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpeg @ 0x1530c01f040] VBV buffer size not set, using default size of 130KB
If you want the mpeg file to be compliant to some specification
Like DVD, VCD or others, make sure you set the correct buffer size
[mpeg4 @ 0x1530bf38e20] The encoder timebase is not set.
[mpeg2video @ 0x1530bf38e20] The encoder timebase is not set.
[mpeg @ 0x1530c01f040] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[mpeg @ 0x1530c01f040] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mpeg @ 0x1530c01f040] VBV buffer size not set, using default size of 130KB
If you want the mpeg file to be compliant to some specification
Like DVD, VCD or others, make sure you set the correct buffer size
[mpeg2video @ 0x1530bf38940] The encoder timebase is not set.
[libtheora @ 0x1530bf38940] The encoder timebase is not set.
[avi @ 0x1530c01f040] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
Ignoring attempt to set invalid timebase 1/0 for st:0
[avi @ 0x1530c01f040] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[libtheora @ 0x1530bf38e20] The encoder timebase is not set.

**Comment by jackburton79** [comment]
I see the same warnings, but recording works. Is recording not working for you ?
In that case, which version of BeScreenCapture are you using ?
On which haiku build ?
Thanks.

**Comment by skarmiglione** [comment]
The last version on the git, for x64 haiku version

**Comment by skarmiglione** [comment]
Maybe can add an option to only get png frames, i can merge them later with blender in or out in other computer, i just want to record the screen no matter if it is on gif or all the frames.png in a folder.

**Comment by jackburton79** [comment]
> Maybe can add an option to only get png frames
I implemented saving the frames as bitmaps in current master, if you are able to compile it you could give it a try.

**Comment by jackburton79** [comment]
Fixed in Haiku since hrev52169
