### ISSUE TITLE
MediaPlayer cannot play videos

### ISSUE THREAD

**Issue by bitigchi** [jackburton79/bescreencapture#43]
This is more likely a Haiku problem, but since it involves files created via BeScreenCapture, leaving this also here. Maybe a slightly different video output can solve the issue.

https://dev.haiku-os.org/ticket/16860

**Comment by jackburton79** [comment]
MPEG/MPEG4 should work. At least, works well on haiku x64.

**Comment by Brunobasta** [comment]
The output.mpg file cannot be played with MediaPlayer, I use VLC or Qmplay2.
MPEG/MPEG4 still does not start on Haiku 64bit nightly

**Comment by jackburton79** [comment]
I can play the mpg file correctly, if I select MPEG/MPEG4 as output format.
Could you post a screenshot of the format you selected ?

**Comment by bitigchi** [comment]
<img width="378" alt="Снимок экрана 2021-11-24 в 12 52 16" src="https://user-images.githubusercontent.com/2769571/143215733-bf242a99-a618-4ffc-a506-44874efaa91b.png">

**Comment by jackburton79** [comment]
AVI doesn't work anymore since Haiku beta3.
If you select mpeg, it should work.

**Comment by bitigchi** [comment]
Would it be possible to make MPEG the default (or remove it altogether for the moment)? It would avoid confusion and problems.

**Comment by jackburton79** [comment]
> Would it be possible to make MPEG the default (or remove it altogether for the moment)? It would avoid confusion and problems.

I guess it's inevitable. I hoped the breakage of the avi would have been fixed in short time, but since so much time has passed, I'll blacklist avi, too, in the next version of BeScreenCapture

**Comment by jackburton79** [comment]
Avi has been blacklisted. MPEG is now the default
