### ISSUE TITLE
Mpeg - mp4 Works but only until 1000 frames is ok for me

### ISSUE THREAD

**Issue by GatoAmarilloBicolor** [jackburton79/bescreencapture#44]
Hello there, i was trying to use bescreencapture, but i constantly have that bug with more than 1000-1200+ frames, if it record more frames then overload the ram and later seems like the virtualmemory have the same luck.

Later of some important minutes 10-20minutes, it can end sucefully or just crash, loosing all the video.

**Comment by jackburton79** [comment]
> Ok, i did try it but cant compile, this is the log on pastebin. https://pastebin.com/7mynTm6K @jackburton79

Beta 3 or nightly ? I could provide a binary if needed.

**Comment by jackburton79** [comment]
The new version is in haikudepot. If you update you should be able to try it.

**Comment by Laniaktroid** [comment]
will test it.

**Comment by Laniaktroid** [comment]
> The new version is in haikudepot. If you update you should be able to try it.

I dit test it, and it work better now, thanks, it still taking some several minutes before to start the encoding movie part, but now it dont eat the all memory as before, is heavy the part of the long time ecoding but now seems more easy to use without a crash or a hang over the all haiku, thanks

It will help to made some videos to show to the new user from bare metal installation.

**Comment by jackburton79** [comment]
Thanks. I will have a look.

**Comment by Laniaktroid** [comment]
> Thanks. I will have a look.

Is there any log or way where can i help you sending info?

**Comment by jackburton79** [comment]
Starting BeScreenCapture from the commandline would show lots of debug info from the ffmpeg addons. You could try doing that.
I would suggest you to wait for the next upcoming release (2.6.0) where I improved some stuff relative to the progress report part.

**Comment by Laniaktroid** [comment]
> Starting BeScreenCapture from the commandline would show lots of debug info from the ffmpeg addons. You could try doing that. I would suggest you to wait for the next upcoming release (2.6.0) where I improved some stuff relative to the progress report part.

Hello, i updated the repo version today, will start to test it, thanks. Later i will add any report.

**Comment by Laniaktroid** [comment]
Hello there, i was testing the vescreen capture, now it can recor until 2000 frames, is faster to decode but if the video is long than 2000 frame it get an error in the decode.
