### ISSUE TITLE
cannot stop or pause BeScreenCapture with default options haiku 32bit nightly

### ISSUE THREAD

**Issue by Brunobasta** [jackburton79/bescreencapture#49]
Installed from HaikuDepot version 2.6.0-1
using default options. 
cannot stop or pause  the process, has to kill the program to stop it.
no outputfile.avi
how to clean the cache then?

**Comment by Brunobasta** [comment]
using ctrl + shift + r does not stop the encoding either

**Comment by jackburton79** [comment]
Is this the First time you used this application? If not, could you try deleting the e settings file in boot/home/config/settings (it's called Bescreencapture)?
 Ctrl-alt-R only works if you install the bescreencapture input filter package

**Comment by Brunobasta** [comment]
I tried delete the settings file but still the same

**Comment by jackburton79** [comment]
I cannot reproduce:
I've tried installing a haiku nightly 32 bit on a VM, with 1GB Ram and 2 vCPU.
Installed BeScreenCapture. Ran with default settings. I managed to start and stop recording. Of course, the default output is AVI so the resulting clip didn't play with MediaPlayer.

**Comment by Brunobasta** [comment]
Haiku  32bit hrev 56640 intel atom 1.6GHz 2GB ram nightly
Still the same isue here with this bescreencaptue release

**Comment by jackburton79** [comment]
Some more info:
Is this a VM or real hardware ?
Could you try launching BeScreenCapture from Terminal, start recording and stop just one second later ? 
Do you see some output in the terminal ?
Thanks!

**Comment by Brunobasta** [comment]
It is on real hardware. I have two haiku 32bit hrev 56645 nightly partitions.
Neither works.
I can start BeScreenCapture fromTerminal but same problem here! How to stop or pause it?
I tried with the hey command to stop it in the other opened terminal. but no way to stop it!
hey BeScreenCapture DO Stop
There is no output at all because I have to kill the process to stop BeScreenCapture!
So no idea what is going on here!
I will try now to do a fresh new install with haiku 32bit beta 4 release candidate now maybe it works on a fresh install... we will see.

**Comment by Brunobasta** [comment]
I am on a fresh! install Haiku 32bit Beta4 RC2 hrev.: 56645
Still the same! I can pause now the process but not resume or stop the record!
No idea what is this all about!?

**Comment by jackburton79** [comment]
Hi!
Please try the new 2.7.0 beta 3, and launch it from commandline.
At least it should show some errors if something goes wrong.

**Comment by jackburton79** [comment]
Version 2.7.0 has been released, and It contains some changes that could fix this issue.
At least another user had this problem, and it's gone now.
Please try.

**Comment by Brunobasta** [comment]
here still all the same! 
No change at all!
Is there a way to run BeScreenCapture from Terminal with some parameter to get some output?

**Comment by jackburton79** [comment]
> here still all the same! 
> No change at all!
> Is there a way to run BeScreenCapture from Terminal with some parameter to get some output?

Yes, I added various printf to stdout. If you start the application from terminal you should get some output as soon as you hit the stop button. Alternatively, 
"Hey BeScreenCapture DO Stop" should stop recording.

**Comment by jackburton79** [comment]
Hi, have you manager to try?

**Comment by jackburton79** [comment]
> here still all the same!
> No change at all!
> Is there a way to run BeScreenCapture from Terminal with some parameter to get some output?

Hi,
did you try from commandline ?

**Comment by Brunobasta** [comment]
Yes I tried everything...
But maybe the Laptop is just to slow or has not enough memory...
