### ISSUE TITLE
BeScreen randomly reduce the screen bright

### ISSUE THREAD

**Issue by GatoAmarilloBicolor** [jackburton79/bescreencapture#51]
Hello, is weird, but sometimes when i use bescreencrapture, my laptop screen bright is reduced almost to the minimun, and this only happen with be screen capture, very strange.

Did you try it on a laptop?

**Comment by jackburton79** [comment]
I would be REALLY surprised if BeScreenCapture could be able to change the screen brightness. I suppose the high CPU usage causes some weird stuff with the acpi or something like that.
Has this ever happened in any other circumstance?

**Comment by Laniaktroid** [comment]
Yes, but then only way i can reproduce it, are whe i use bescreen capture.

**Comment by jackburton79** [comment]
Hi, could you try with v2.7.0 beta 3 ?
