### ISSUE TITLE
New and re-ordered menu items

### ISSUE THREAD

**Issue by humdingerb** [jackburton79/bescreencapture#60]
Just a suggestion. As opening the help file and the "About" both concern the app, and the "Quit" item is so very lonesome there, those items may be moved back into the "App" menu. I suggest:

* App
"Help... ALT+H"  (to open the doc)
"About BeScreenCapture" (it's good practise to include the app name here)
---- (Separator)
"Quit ALT+Q"

* Recording
"Start ALT+S" (disasable while recording)
"Stop ALT+T" (only enable when recording)
---- (Separator"
"Pause ALT+P" (this one should have a checkmark)

* Settings
"Reset to defaults ALT+R"

**Comment by jackburton79** [comment]
Looks nice. I just have some doubts about ALT+R: since the start combo is CTRL+ALT+SHIFT+R, I hope it doesn't clash with it.

**Comment by humdingerb** [comment]
Maybe "ALT+D" then, for "defaults"?

**Comment by jackburton79** [comment]
Done. I didn't add a shortcut for Settings.. defaults, though, since I think it's overkill.

**Comment by humdingerb** [comment]
Fair enough. :)
