### ISSUE TITLE
Program memory usage issues

### ISSUE THREAD

**Issue by MilkGolium** [jackburton79/bescreencapture#66]
Hi,
I was trying to record something on Haiku R1/Beta2 but ran into some issues. The program's memory usage kept increasing while recording, until it ran out of memory, using swap space and causing system freezes. 

Another issue was that after finishing recording and encoding, the memory was not automatically released, and I had to exit the program to do so.

Thanks!

[video.zip](https://github.com/user-attachments/files/16312145/video.zip)
CPU: Intel Celeron 1037U 1.8Ghz
RAM: 2GB 1333MHz
Disk: Seagate HDD 500GB SATA

**Comment by jackburton79** [comment]
Is it really Beta/2?
I recall a memory leak in haiku mediakit which was fixed at some point. Might be that one (or a new one if you meant beta/4)

**Comment by jackburton79** [comment]
Ok, I found the leak in BeScreenCapture. It's a regression. Fixing now.

**Comment by jackburton79** [comment]
Thanks for the report! It's fixed in the new release (2.9.1) which should be merged soon in Haikuports.

**Comment by MilkGolium** [comment]
> Is it really Beta/2? I recall a memory leak in haiku mediakit which was fixed at some point. Might be that one (or a new one if you meant beta/4)

Oh, I'm so sorry, it's beta4, I wrote it wrong.

**Comment by jackburton79** [comment]
No worries it was my fault in the end 😅
